# Generated by Django 6.0.5 on 2026-05-07 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Politician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abgeordnetenwatch_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "party",
                    models.CharField(
                        choices=[
                            ("SPD", "SPD"),
                            ("CDU/CSU", "CDU/CSU"),
                            ("Grüne", "Grüne"),
                            ("AfD", "AfD"),
                            ("Die Linke", "Die Linke"),
                            ("FDP", "FDP"),
                        ],
                        max_length=50,
                    ),
                ),
                ("parliament", models.CharField(max_length=100)),
                ("image_url", models.URLField(blank=True)),
                ("image_local", models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=40)),
                ("guessed_party", models.CharField(max_length=50)),
                ("is_correct", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "politician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="guesstheparty.politician",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
