# Generated by Django 5.1.3 on 2026-05-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesstheparty', '0002_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
