# Generated by Django 5.1.3 on 2026-05-10 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesstheparty', '0004_answer_is_spectrum_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='pending_politician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='guesstheparty.politician'),
        ),
    ]
