# Generated by Django 5.1.3 on 2026-05-10 17:58

from django.db import migrations, models
from django.utils.text import slugify


def backfill_reference(apps, schema_editor):
    Politician = apps.get_model("guesstheparty", "Politician")
    seen = set(
        Politician.objects.exclude(reference="").values_list("reference", flat=True)
    )
    to_update = []
    for politician in Politician.objects.filter(reference="").order_by("id"):
        base = slugify(politician.name)
        candidate = base
        if candidate in seen:
            candidate = f"{base}-{slugify(politician.party)}"
        if candidate in seen:
            raise ValueError(
                f"Could not generate unique reference for '{politician.name}' ({politician.party})"
            )
        politician.reference = candidate
        seen.add(candidate)
        to_update.append(politician)
    Politician.objects.bulk_update(to_update, ["reference"])


class Migration(migrations.Migration):

    dependencies = [
        ("guesstheparty", "0005_usersession_pending_politician"),
    ]

    operations = [
        migrations.AddField(
            model_name="politician",
            name="reference",
            field=models.SlugField(blank=True, max_length=250),
        ),
        migrations.RunPython(backfill_reference, migrations.RunPython.noop),
    ]
