# Generated by Django 5.1.3 on 2026-05-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesstheparty', '0008_alter_politician_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='author_name',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
