# Generated by Django 5.1.3 on 2026-05-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guesstheparty", "0011_backfill_session_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="politician",
            name="thumbnail_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
